routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('logs', 'JobLogController')->only(['index', 'show', 'destroy']);

Auth::routes();
Route::get('/logs/{type}/{id}', 'JobLogController@showGroup');
Route::get('/jobs', 'JobController@index')->name('jobs.index');
Route::get('/jobs/watch', 'JobController@watch')->name('jobs.watch');
Route::get('/job/{job}/show', 'JobController@show')->name('jobs.show');
Route::get('/job/{job}', 'JobController@create')->name('jobs.create');
Route::post('/job/{job}', 'JobController@store');

resources/views/_menu.blade.php
<div >
    <div class="card">
        <div class="card-header">Menu</div>
        <div class="list-group list-group-flush">
            <a class="list-group-item list-group-item-action"
               href="/horizon" target="_blank">
                Horizon
            </a>
            <a class="list-group-item list-group-item-action"
               href="{{route('dummyJob')}}">
                Run DummyJob
            </a>
            <a class="list-group-item list-group-item-action"
               href="{{route('logs.index')}}">
                Logs
            </a>
            <a class="list-group-item list-group-item-action"
               href="{{route('jobs.index')}}">
                Jobs
            </a>
        </div>
    </div>
</div>
<br>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection