routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('logs', 'JobLogController')->only(['index', 'show', 'destroy']);

Auth::routes();
Route::get('/logs/{type}/{id}', 'JobLogController@showGroup');
Route::get('/jobs', 'JobController@index')->name('jobs.index');
Route::get('/jobs/watch', 'JobController@watch')->name('jobs.watch');
Route::get('/job/{job}/show', 'JobController@show')->name('jobs.show');
Route::get('/job/{job}', 'JobController@create')->name('jobs.create');
Route::post('/job/{job}', 'JobController@store');

resources/views/logs/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @include('flash::message')
        <div class="row justify-content-center">
            @include('_menu')
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Logs</div>
                    <div class="card-body">
                        <table class="table table-hover table-striped table-sm">
                            <thead>
                            <tr>
                                <th scope="col">Job</th>
                                <th scope="col">Records</th>
                                <th scope="col">Last update</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            @forelse ($logs as $log)
                                <tr>
                                    <td>{{$log->loggable_type}}:{{$log->loggable_id}}</td>
                                    <td>{{$log->total}}</td>
                                    <td>{{$log->created_at}}</td>
                                    <td><a class="btn btn-sm btn-primary" href="{{route('logs.show', ['log'=>$log]) }}">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" class="table-info"> No records</td>
                                </tr>
                            @endforelse
                        </table>
                    </div>
                    <div class="card-footer">
                        {{$logs->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/logs/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @include('flash::message')
        <div class="row justify-content-center">
            @include('_menu')
            <div class="col-md-8">
                <h4>Logs for {{$group->loggable_type}}: {{$group->loggable_id}}</h4>
                <form action="{{route('logs.destroy', ['log'=>$group])}}" method="POST">
                    @method('DELETE') @csrf
                    <button type="submit" class="btn btn-sm btn-danger">
                        <i class="fa fa-trash-o"></i> Delete
                    </button>
                </form>
                @foreach ($logs as $log)
                    <div class="card">
                        <div class="card-header">
                            <div class="badge badge-info">{{$log->level}}</div>
                            <div class="badge badge-dark">{{$log->created_at}}</div>
                        </div>
                        <div class="card-body">
                            {{$log->message}}
                            {{$log->context ?? ''}}
                            {{$log->extra ?? ''}}
                        </div>
                    </div>
                @endforeach
                <div>
                    {{$logs->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection